// <auto-generated />
using System;
using DF_NTCong_Repo_Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DF_NTCong_Repo_Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230426155931_Init_V01")]
    partial class Init_V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DF_NTCong_Repo_Core.Models.Product_Table", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Products__3213E83FC142A735");

                    b.ToTable("Product_Table");
                });

            modelBuilder.Entity("DF_NTCong_Repo_Core.Models.Sinhvien", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<decimal?>("Hocphi")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("HOCPHI");

                    b.Property<string>("Khoahoc")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("char(25)")
                        .HasColumnName("KHOAHOC")
                        .IsFixedLength();

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TEN");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int")
                        .HasColumnName("TUOI");

                    b.HasKey("Id")
                        .HasName("PK__SINHVIEN__3214EC2758545D8C");

                    b.ToTable("SINHVIEN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
